name: Build

on:
  push:

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Remove PackageVersion
        uses: ./
        with:
          owner: ${{secrets.bnauk_user}}
          token: ${{secrets.bnauk_token}}
          organization: 'bnauk'
          packageName: 'com.bnauk.bbcron.bbcron-api'
          packageVersion: '0.0.3-SNAPSHOT'

      #- name: Publish to GitHub Packages Apache Maven
      #  env:
      #    GITHUB_USER: ${{secrets.bnauk_user}}
      #    GITHUB_TOKEN: ${{secrets.bnauk_token}}
      #  run: mvn -X -s settings.xml -B -Dchangelist=-SNAPSHOT deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/3nauk/maven-site

