name: Build

on:
  push:

jobs:
  test-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Remove PackageVersion
        uses: ./
        with:
          organization: '3nauk'
          packageName: 'com.bnauk.bbcron.bbcron-api'
          packageVersion: '0.0.3-SNAPSHOT'
          token: ${{secrets.bnauk_token}}

      #- name: Publish to GitHub Packages Apache Maven
      #  env:
      #    GITHUB_USER: ${{secrets.bnauk_user}}
      #    GITHUB_TOKEN: ${{secrets.bnauk_token}}
      #  run: mvn -X -s settings.xml -B -Dchangelist=-SNAPSHOT deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/3nauk/maven-site

